services:
  azuresql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresql-order-etl
    hostname: mssql-order-etl
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
      MSSQL_PID: "Standard"
      TZ: "Asia/Bangkok"
    volumes:
      - azuresql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  azuresql_data:
